### ISSUE TITLE
bug? check の標準エラー出力のリダイレクト先がおかしい気がします

### ISSUE THREAD

**Issue by yoshi389111** [Qithub-BOT/QiiCipher#10]
check コマンドに以下のような記述があります。

```sh
RESULT=`enc ${USERNAME} ${PATHFILE} 2>$1`
```

```sh
RESULT=`dec ${SECRETKEY} ${PATHFILE}.enc ${PATHFILE}.dec 2>$1`
```

このコマンドの場合、第一引数 `$1` はgithubのユーザー名なので、ユーザー名のファイルに標準エラー出力が出力されてしまいます。

おそらく `2>&1` （標準出力と合わせる）あるいは `2>&-` （標準エラー出力を閉じる）のどちらかが正しいのではないかと思います。
（個人的には、削除して画面に出力してもよい気がしますが）

**Comment by KEINOS** [comment]
あー！！これはバグですね。`2>&1` です。

これは、出力ファイルをログ代わりにする意図がありました。

コンソール上だとエラーを見逃したユーザの対応が面倒なのと、ファイルの中身を教えてもらえば少なくとも内容がわかる、という感じを想定していました。

「なんか知らないファイルができている」という問い合わせをもらったことがあるのですが、 `enc` ファイルのことだと思っていました。もしかすると、このユーザ名のファイルのことだったのかもしれません。

やはりテストが必要だなー。ご報告ありがとうございます！
