### ISSUE TITLE
shellcheck および shellfmt の導入

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/QiiCipher#3]
QiiCipher v2（次期バージョン）では、スクリプト内の処理を関数化して各々テストを設けたいが、その前に `shellcheck` による静的解析と、`shfmt` による lint チェック環境を用意したい。

- [shellcheck](https://github.com/koalaman/shellcheck) @ GitHub
- [shfmt](https://github.com/mvdan/sh) @ GitHub

**Comment by yoshi389111** [comment]
参考資料のメモです

## shellcheck

Qiita記事 [GitHub Actions を用いて Pull-Request で shellcheck をする方法](https://qiita.com/osakiy/items/27d5382e41107de482a4)

GitHub Actions のデフォルト環境(Ubuntuのみ)には shellcheck が入っている

* [GitHub Actions Virtual Environments](https://github.com/actions/virtual-environments)
  * [ubuntu-20.04](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md) - shellcheck 0.7.0-2build2
  * [ubuntu-18.04](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md) - shellcheck 0.4.6-1

shellcheck GitHub リポジトリ

* https://github.com/koalaman/shellcheck

shellcheck オフィシャルのdockerイメージ

* https://hub.docker.com/r/koalaman/shellcheck/

Web 上で shellcheck を実行

* https://www.shellcheck.net/

## shfmt

shfmt GitHub リポジトリ

* https://github.com/mvdan/sh

shfmt オフィシャルのdockerイメージ

* https://hub.docker.com/r/mvdan/shfmt
