### ISSUE TITLE
コマンドの引数が間違えていた場合のメッセージ改善

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/QiiCipher#33]
下記は**引数の順番を間違えている**のに、公開鍵のアクセス権に問題があるように見えます。

```shellsession
$ verify ~/.ssh/github hello.txt emadurandal

/home/emadurandal/.ssh/github を電子署名 emadurandal で検証します

- hello.txt の GitHub 上の公開鍵を取得中 ... OK
- RSA 形式の公開鍵を PKCS8 形式に変換中 ... @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0664 for '/tmp/verify-/hello.txt.pub' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
Load key "/tmp/verify-/hello.txt.pub": bad permissions
NG：RSA -> PKCS8 変換中にエラーが発生しました。
```
（Issue #31 より）

引数の順番の検知、もしくはエラー内容に引数の順番に間違いがないかなど、もう少しユーザに優しくてもいいと思います。

**Comment by yoshi389111** [comment]
全体的に入力チェックを厳しくするという話なのかもしれませんが、とりあえず `curl` のエラーが取得できていないのも１つの原因だと思うので、それについて調査しました。

## 調査

現在の `curl` で公開鍵を取得する処理は以下のような感じになっています。

```shell
if ! curl -s "https://github.com/${USERNAME}.keys" | head -n 1 >"$PATHPUBKEY"; then
    echo "NG：公開鍵を取得・保存できませんでした。"
    exit 1
fi
```

上記処理の curl で `404 not found` が起きても、どうやら続行してしまうようです(Ubuntu で確認)。
問題は２つありそう。

１つ目は、`curl` が `404 not found` の場合にエラーメッセージを標準出力に出力して、正常終了をしていることです。
（以下の例では、エラーメッセージとして "Not Found" （改行無し）を出力している）

```shell-session
$ curl -s https://github.com/hello.txt.keys
Not Found$ echo $?
0
```

対策としては `curl` に `--fail` を指定して、エラーメッセージを出力せず、終了コードを 0 以外にすることだと思います。

```shell-session
$ curl --fail -s https://github.com/hello.txt.keys
$ echo $?
22
```

２つ目は、`curl` の終了コードが、パイプのため握りつぶされていることです。

```shell-session
$ exit 1 | exit 0
$ echo $?
0
```

対策はパイプをやめてファイル経由で処理するか、出力した公開キーが空でないことをチェックするかでしょうか。
（以下は、公開キーが空の場合にエラーとしている例）

```shell
curl --fail -s "https://github.com/${USERNAME}.keys" | head -n 1 >"$PATHPUBKEY"
if [ ! -s "$PATHPUBKEY" ]; then
    echo "NG：公開鍵を取得・保存できませんでした。"
    exit 1
fi
```

## 影響範囲

`curl` で公開鍵を取得しているのは以下の４本
（今回の物も含めて、同様の処理をしているコマンド）

* `checkkeylength`
* `enc`
* `sign`
* `verify`

また、パイプでつないで終了コードを判定しているものは上記以外では、以下があります。

* `archive`

```shell
if ! (tar cz "$INPUTFILE" | openssl enc -e -aes-256-cbc -salt -k "$PASSWORD" -out "${TEMPDIR}${OUTPUTFILE}"); then
    echo "NG：ファイルを圧縮・暗号化できませんでした。"
    exit 1
fi
```
