### ISSUE TITLE
shellspec テストのステータスバッジが "no status" のまま

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/QiiCipher#45]
dde7df6 現在、[shellspec のテストはパスしている](https://github.com/Qithub-BOT/QiiCipher/actions/workflows/shellspec_linux.yml)もステータスが "no status" のままです。

<kbd><img src="https://user-images.githubusercontent.com/11840938/120738476-deab5200-c52a-11eb-9fc9-21de9dc3237e.png" width="100%" /></kbd>

手動でテストを走らせてパスするも、NG。CDN のキャッシュかなと思ったのですが、強制リロードでも変わらず。

<kbd><img src="https://user-images.githubusercontent.com/11840938/120738859-83c62a80-c52b-11eb-9a34-773321a06208.png" width="100%" /></kbd>

なぜだ ...

- リアルタイム: ![](https://github.com/Qithub-BOT/QiiCipher/actions/workflows/shellspec_linux.yml/badge.svg)

**Comment by yoshi389111** [comment]
私の環境だと passing になっていますね。 `dde7df6`

**Comment by KEINOS** [comment]
ありゃ、以下の URL を叩いたら更新された。

https://github.com/Qithub-BOT/QiiCipher/actions/workflows/shellspec_linux.yml/badge.svg

- [Using the workflow file name](https://docs.github.com/en/actions/managing-workflow-runs/adding-a-workflow-status-badge#using-the-workflow-file-name) | Adding a workflow status badge @ docs.github.com

**Comment by KEINOS** [comment]
ってか、URL 変わってないや。やっぱり、こっちのキャッシュの問題かも新米。

一旦クローズして、再発したら考えましょう。

**Comment by KEINOS** [comment]
@yoshi389111 確認ありがとうございます。やっぱり、おいどんローカルだけの現象のようです。お騒がせしましたー
