### ISSUE TITLE
[POSIX準拠] $RANDOM を OpenSSL で代替

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/QiiCipher#49]
## そうね代替ねぇ〜♪

https://github.com/Qithub-BOT/QiiCipher/blob/b90eaa71dca3a4d73549557e0f1863fb3e5781f6/bin/check#L22-L28

上記 `md5r()` で使われている `$RANDOM` は POSIX 環境では定義されないので、必須である `openssl` にまかせてしまおうというリファクタです。

下記、参考先にサンプルとテストがあるので、流用してください。

- 参考 https://github.com/Qithub-BOT/QiiCipher/discussions/39#discussioncomment-824296

**Comment by yoshi389111** [comment]
#53 で対応したのでクローズします
